gui:
  showIcons: true

keybinding:
  universal:
    undo: '<C-Z>'
    redo: 'z'
    submitEditorText: '<A-Enter>'
    appendNewline: '<Enter>'
  files:
    commitChanges: 'C'
    commitChangesWithEditor: 'c'
  commits:
    renameCommit: 'R'
    renameCommitWithEditor: 'r'

# Mac user : Copy this file to ~/Library/Application Support/lazygit/
